# SPDX-License-Identifier: Apache-2.0
fixtures:
    symlinks:
        apereo_cas: "#{source_dir}"
        stdlib: "../../../../stdlib"
        wmflib: "../../../../wmflib"
        network: "../../../../git"
