inherit_from: .rubocop_todo.yml

# Copied from
# https://www.mediawiki.org/wiki/Manual:Coding_conventions/Ruby#Base_configuration
# and modified

AllCops:
  StyleGuideCopsOnly: true
  DisplayCopNames: true
  Exclude:
    # not a Ruby script
    - 'modules/smokeping/files/smokeping.fcgi'
    # third party modules
    - 'modules/mysql/**/*'
    - 'modules/rsync/**/*'
    - 'modules/stdlib/**/*'
    - 'modules/puppetdbquery/**/*'
    - 'modules/lvm/**/*'
    # bundler installation files
    - 'vendor/**/*'
    - '**/Vagrantfile'

# Uncomment when lines are 100 characters or less
# Metrics/LineLength:
#   Max: 100

Metrics/MethodLength:
  Enabled: false

Style/Alias:
  Enabled: false

# Let us whatever delimiters we want eg: %{One Two} or %r%/tmp%
Style/PercentLiteralDelimiters:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/TrivialAccessors:
  ExactNameMatch: true

Style/WordArray:
  Enabled: false

# should be fixed with %i[] in Ruby >= 2.0 (>= jessie)
Style/SymbolArray:
  Enabled: false

# we can't depend on ActiveRecord etc., but we can use squiggly heredocs (<<~)
# when we move to Ruby >= 2.3 (>= stretch)
Layout/IndentHeredoc:
  Enabled: false

# bad advice
Style/GuardClause:
  Enabled: false

# We still have to support ruby 2.1 because of jessie however i suspect many users have there
# editor lint checks set to a higher ruby version hence the warnings
Lint/UnneededDisable:
  Enabled: false
