cluster: prometheus
profile::base::domain_search:
  - wikimedia.org
  - eqiad.wmnet
  - codfw.wmnet
  - esams.wmnet
  - ulsfo.wmnet
  - eqsin.wmnet
prometheus::server::mysqld_exporter::mysql::host: db1115.eqiad.wmnet
prometheus::server::mysqld_exporter::mysql::port: 3306
prometheus::server::mysqld_exporter::mysql::database: zarcillo
prometheus::server::mysqld_exporter::mysql::user: prometheus-mysqld-exporter
# prometheus::server::mysqld_exporter::mysql::password: stored on the private repo

profile::prometheus::k8s::staging::thanos: true
profile::prometheus::analytics::thanos: true
profile::prometheus::services::thanos: true
profile::prometheus::k8s::thanos: true

profile::lvs::realserver::use_conftool: true
profile::lvs::realserver::pools:
  prometheus:
    services:
      - prometheus@analytics
      - prometheus@global
      - prometheus@k8s
      - prometheus@k8s-staging
      - prometheus@ops
      - prometheus@services
