fixtures:
    symlinks:
        zuul: "#{source_dir}"
        apt: "../../../../apt"
        git: "../../../../git"
        stdlib: "../../../../stdlib"
        systemd: "../../../../systemd"
        wmflib: "../../../../wmflib"
