profile::alertmanager::irc::nickname: 'jinxer-wm-test'
profile::alertmanager::irc::nickname_password: 'dummy'
profile::alertmanager::irc::channel: 'wikimedia-o11y-test'

profile::alertmanager::web::vhost: "alerts.%{lookup('public_domain')}"

alertmanagers: "%{alias('__hosts_for_role_alerting_host')}"

profile::alertmanager::active_host: "%{alias('__master_for_role_alerting_host')}"
profile::alertmanager::partners: "%{alias('__hosts_for_role_alerting_host')}"
