prometheus::server::storage_retention: '768h'
profile::lvs::realserver::use_conftool: false
prometheus_nodes: "%{alias('__hosts_for_role_prometheus')}"
prometheus_all_nodes: "%{alias('__hosts_for_role_prometheus')}"
