cluster: prometheus
profile::prometheus::ops::enable_thanos_upload: true
profile::base::domain_search:
  - wikimedia.org
  - eqiad.wmnet
  - codfw.wmnet
  - esams.wmnet
  - ulsfo.wmnet
  - eqsin.wmnet
