groups:
 - name: blackbox
   rules:
   - alert: ProbeDown
     annotations:
       description: '{{ $labels.instance }} has failed its {{ $labels.module }} probe'
       summary: 'Service {{ $labels.instance }} has failed probes'
     # Availability is less than 80%
     expr: avg_over_time(probe_success{job="blackbox/discovery"}[1m]) * 100 < 80
     for: 0m
     labels:
       severity: warning

   - alert: ProbeSlow
     annotations:
       description: '{{ $labels.instance }} took {{ $value | humanizeDuration }} to reply successfully to probe {{ $labels.module }}'
       summary: 'Successful but slow probes for service {{ $labels.instance }}'
     expr: probe_duration_seconds{job="blackbox/discovery"} * probe_success > 1
     for: 2m
     labels:
       severity: warning
