- labels:
    shard: m1
    role: master
  targets:
  - db1063:9104

- labels:
    shard: m1
    role: slave
  targets:
  - db1117:13321
  - db1135:9104

- labels:
    shard: m2
    role: master
  targets:
  - db1132:9104

- labels:
    shard: m2
    role: slave
  targets:
  - db1065:9104
  - db1117:13322

- labels:
    shard: m3
    role: master
  targets:
  - db1072:9104

- labels:
    shard: m3
    role: slave
  targets:
  - db1117:13323
  - db1128:9104

- labels:
    shard: m4
    role: master
  targets:
  - db1107:9104

- labels:
    shard: m4
    role: slave
  targets:
  - db1108:9104

- labels:
    shard: m5
    role: master
  targets:
  - db1073:9104

- labels:
    shard: m5
    role: slave
  targets:
  - db1117:13325
  - db1133:9104

- labels:
    shard: tendril
    role: standalone
  targets:
  - db1115:9104

