- labels:
    shard: s1
    role: slave
  targets:
  - dbstore1001:13311

- labels:
    shard: s2
    role: slave
  targets:
  - db1095:13312

- labels:
    shard: s3
    role: slave
  targets:
  - db1095:13313

- labels:
    shard: s4
    role: slave
  targets:
  - db1102:13314

- labels:
    shard: s5
    role: slave
  targets:
  - db1102:13315

- labels:
    role: slave
    shard: multi
  targets:
  - dbstore1002:9104
