- labels:
    shard: s1
    role: slave
  targets:
  - dbstore2002:13311
  - db2097:13311

- labels:
    shard: s2
    role: slave
  targets:
  - dbstore2001:13312
  - db2098:13312

- labels:
    shard: s3
    role: slave
  targets:
  - dbstore2002:13313
  - db2098:13313

- labels:
    shard: s4
    role: slave
  targets:
  - dbstore2002:13314
  - db2099:13314

- labels:
    shard: s5
    role: slave
  targets:
  - dbstore2001:13315
  - db2099:13315

- labels:
    shard: s6
    role: slave
  targets:
  - dbstore2001:13316
  - db2097:13316

- labels:
    shard: s7
    role: slave
  targets:
  - dbstore2001:13317

- labels:
    shard: s8
    role: slave
  targets:
  - dbstore2001:13318

- labels:
    shard: x1
    role: slave
  targets:
  - dbstore2002:13320

