profile::prometheus::ops::blackbox_watchrat_http_check_urls:
- https://de.wikipedia.org/wiki/Main_Page
- https://donate.wikimedia.org/
- https://dsb.wikipedia.org/wiki/Main_Page
- https://dumps.wikimedia.org/backup-index.html
- https://en.wikinews.org/wiki/Main_Page
- https://en.wikipedia.org/wiki/Special:Random
- https://en.wikiquote.org/wiki/Main_Page
- https://en.wikisource.org/wiki/Main_Page
- https://en.wikiversity.org/wiki/Main_Page
- https://en.wikivoyage.org/wiki/Main_Page
- https://en.wiktionary.org/wiki/Main_Page
- https://fi.wikipedia.org/wiki/Main_Page
- https://fr.wikipedia.org/wiki/Main_Page
- https://frdata.wikimedia.org/
- https://login.wikimedia.org/wiki/Main_Page
- https://meta.wikimedia.org/w/resources/assets/poweredby_mediawiki_88x31.png
- https://payments-listener.wikimedia.org/globalcollect
- https://payments.wikimedia.org/index.php/Special:SystemStatus
- https://secure.wikimedia.org/wikipedia/en/wiki/Main_Page
- https://store.wikimedia.org
- https://shop.wikimedia.org
- https://uk.wikipedia.org/wiki/Main_Page
- https://wikimedia.org
- https://wikimediafoundation.org/wiki/Home
- https://www.mediawiki.org/wiki/MediaWiki
- https://www.wiktionary.org
