# SPDX-License-Identifier: Apache-2.0
---
lowercaseOutputLabelNames: true
lowercaseOutputName: false
whitelistObjectNames:
  - 'Hadoop:service=NodeManager,name=NodeManagerMetrics'
  - 'Hadoop:service=NodeManager,name=ShuffleMetrics'