# SPDX-License-Identifier: Apache-2.0
---
lowercaseOutputLabelNames: true
lowercaseOutputName: false
whitelistObjectNames:
  - 'Hadoop:service=NameNode,name=FSNamesystem'
  - 'Hadoop:service=NameNode,name=NameNodeActivity'
  - 'Hadoop:service=NameNode,name=RpcActivityForPort*'