# SPDX-License-Identifier: Apache-2.0
---
lowercaseOutputLabelNames: true
lowercaseOutputName: false
whitelistObjectNames:
  - 'Hadoop:service=JournalNode,name=Journal?*'
  - 'Hadoop:service=JournalNode,name=RpcActivityForPort8485'