# SPDX-License-Identifier: Apache-2.0
---
lowercaseOutputLabelNames: true
lowercaseOutputName: false
whitelistObjectNames:
  - 'Hadoop:service=DataNode,name=DataNodeActivity*'
  - 'Hadoop:service=DataNode,name=FSDatasetState*'