fixtures:
    symlinks:
        profile: "#{source_dir}"
        apt: "../../../../apt"
        backup: "../../../../backup"
        base: "../../../../base"
        conftool: "../../../../conftool"
        deployment: "../../../../deployment"
        etcd: "../../../../etcd"
        envoyproxy: "../../../../envoyproxy"
        ferm: "../../../../ferm"
        git: "../../../../git"
        hhvm: "../../../../hhvm"
        httpd: "../../../../httpd"
        ldap: "../../../../ldap"
        logrotate: "../../../../logrotate"
        lvs: "../../../../lvs"
        mediawiki: "../../../../mediawiki"
        monitoring: "../../../../monitoring"
        mtail: "../../../../mtail"
        network: "../../../../network"
        nginx: "../../../../nginx"
        nrpe: "../../../../nrpe"
        phabricator: "../../../../phabricator"
        php: "../../../../php"
        rsync: "../../../../rsync"
        rsyslog: "../../../../rsyslog"
        sslcert: "../../../../sslcert"
        stdlib: "../../../../stdlib"
        sysctl: "../../../../sysctl"
        systemd: "../../../../systemd"
        tlsproxy: "../../../../tlsproxy"
        wmflib: "../../../../wmflib"
