fixtures:
    symlinks:
        profile: "#{source_dir}"
        sslcert: "../../../../sslcert"
        wmflib: "../../../../wmflib"
        ldap: "../../../../ldap"
        lvs: "../../../../lvs"
        phabricator: "../../../../phabricator"
