# SPDX-License-Identifier: Apache-2.0
fixtures:
    symlinks:
        aptrepo: "#{source_dir}"
        apt: "../../../../apt"
        ssh: "../../../../ssh"
        wmflib: "../../../../wmflib"
        stdlib: "../../../../stdlib"
