# Main microservices
restbase-async: [eqiad, codfw]
restbase-backend: [eqiad, codfw]
restbase: [eqiad, codfw]
search: [eqiad, codfw]
# All the rest
apertium: [eqiad, codfw]
api-gateway: [eqiad, codfw]
aqs: [eqiad]
blubberoid: [eqiad, codfw]
citoid: [eqiad, codfw]
cxserver: [eqiad, codfw]
docker-registry: [eqiad, codfw]
druid-public-broker: [eqiad]
echostore: [eqiad, codfw]
eventgate-analytics: [eqiad, codfw]
eventgate-analytics-external: [eqiad, codfw]
eventgate-logging-external: [eqiad, codfw]
eventgate-main: [eqiad, codfw]
eventstreams: [eqiad, codfw]
eventstreams-internal: [eqiad, codfw]
helm-charts: [eqiad, codfw]
kartotherian: [eqiad, codfw]
kibana: [eqiad, codfw]
linkrecommendation: [eqiad, codfw]
logstash: [eqiad]
mathoid: [eqiad, codfw]
mobileapps: [eqiad, codfw]
mwdebug: [eqiad, codfw]
ores: [eqiad, codfw]
proton: [eqiad, codfw]
push-notifications: [eqiad, codfw]
recommendation-api: [eqiad, codfw]
releases: [eqiad, codfw]
schema: [eqiad, codfw]
sessionstore: [eqiad, codfw]
shellbox: [eqiad, codfw]
similar-users: [eqiad, codfw]
termbox: [eqiad, codfw]
thanos-query: [eqiad, codfw]
thanos-swift: [eqiad, codfw]
wdqs: [eqiad, codfw]
wdqs-internal: [eqiad, codfw]
wikifeeds: [eqiad, codfw]
zotero: [eqiad, codfw]
puppetdb-api: [eqiad, codfw]
