# SPDX-License-Identifier: Apache-2.0
fixtures:
    symlinks:
        osm: "#{source_dir}"
        stdlib: "../../../../stdlib"
        wmflib: "../../../../wmflib"
        logrotate: "../../../../logrotate"
