profile::restbase::seeds_ng:
  - restbase2007-a.codfw.wmnet
  - restbase2007-b.codfw.wmnet
  - restbase2007-c.codfw.wmnet
  - restbase2008-a.codfw.wmnet
  - restbase2008-b.codfw.wmnet
  - restbase2008-c.codfw.wmnet
  - restbase2009-a.codfw.wmnet
  - restbase2009-b.codfw.wmnet
  - restbase2009-c.codfw.wmnet
  - restbase2010-a.codfw.wmnet
  - restbase2010-b.codfw.wmnet
  - restbase2010-c.codfw.wmnet
# used for rate limiting
profile::restbase::hosts:
  - restbase2007.codfw.wmnet
  - restbase2008.codfw.wmnet
  - restbase2009.codfw.wmnet
  - restbase2010.codfw.wmnet
  - restbase2011.codfw.wmnet
  - restbase2012.codfw.wmnet
  - restbase2013.codfw.wmnet
  - restbase2014.codfw.wmnet
  - restbase2015.codfw.wmnet
  - restbase2016.codfw.wmnet
  - restbase2017.codfw.wmnet
  - restbase2018.codfw.wmnet
  - restbase2019.codfw.wmnet
  - restbase2020.codfw.wmnet

lvs::realserver::realserver_ips:
  - '10.2.1.17' # restbase.svc.codfw.wmnet
