fixtures:
    symlinks:
      authdns: "#{source_dir}"
      apt: "../../../../apt"
      geoip: "../../../../geoip"
      wmflib: "../../../../wmflib"
      stdlib: "../../../../stdlib"
      nrpe: "../../../../nrpe"
      monitoring: "../../../../monitoring"
