fixtures:
    symlinks:
        wdqs: "#{source_dir}"
        base: "../../../../base"
        diamond: "../../../../diamond"
        ferm: "../../../../ferm"
        java: "../../../../java"
        monitoring: "../../../../monitoring"
        ssh: "../../../../ssh"
        sudo: "../../../../sudo"
        icinga: "../../../../icinga"
        systemd: "../../../../systemd"
        service: "../../../../service"
        scap: "../../../../scap"
        stdlib: "../../../../stdlib"
        wmflib: "../../../../wmflib"
