profile::base::purge_apt_sources: true
profile::base::purge_apt_preferences: true
profile::base::use_apt_proxy: true
profile::base::manage_apt_source: true
profile::base::apt_install_audit_installed: true
profile::base::mirror_server: 'deb.debian.org'
