profile::environment::ls_aliases: true
profile::environment::export_systemd_env: true
profile::environment::custom_bashrc: null
profile::environment::custom_skel_bashrc: null
profile::environment::custom_skel_zshrc: null
profile::environment::editor: 'vim'
profile::environment::wikimedia_domains: []
profile::environment::no_proxy_domains: []
profile::environment::skip_domains: []
profile::environment::profile_scripts:
  field.sh: 'puppet:///modules/base/environment/field.sh'
  mysql-ps1.sh: 'puppet:///modules/base/environment/mysql-ps1.sh'
  bash_autologout.sh: 'puppet:///modules/base/environment/bash_autologout.sh'
profile::environment::variables: {}
