profile::openldap::hostname: cloudservices2004-dev.wikimedia.org
profile::openldap::mirror_mode: true
profile::openldap::backup: false
profile::openldap::server_id: 1
profile::openldap::master: cloudservices2004-dev.wikimedia.org
profile::openldap::hash_passwords: SHA
profile::openldap::read_only: false
profile::openldap::certname: ldap-codfw1dev
profile::openldap::storage_backend: hdb
profile::openldap::sync_pass: none
profile::monitoring::notifications_enabled: false
profile::admin::groups:
  - wmcs-roots
  - labtest-roots
# See T224828
raid::md::timer_ensure: absent
profile::contacts::role_contacts: ['WMCS']

# prometheus-pdns-exporter is scraped by cloudmetrics
# prometheus-node-exporter by prod servers
prometheus_nodes:
    - cloudmetrics1003.eqiad.wmnet
    - cloudmetrics1004.eqiad.wmnet
    - prometheus2005.codfw.wmnet
    - prometheus2006.codfw.wmnet
