profile::calico::kubernetes::etcd_endpoints:
- https://kubestagetcd1004.eqiad.wmnet:2379
- https://kubestagetcd1005.eqiad.wmnet:2379
- https://kubestagetcd1006.eqiad.wmnet:2379
profile::calico::kubernetes::bgp_peers:
- kubestage1001.eqiad.wmnet
- kubestage1002.eqiad.wmnet
- cr1-eqiad.wikimedia.org
- cr2-eqiad.wikimedia.org
# TODO: Migrate to k8s API, calico v2.2 doesn't support anything than etcdv2
profile::calico::kubernetes::calico_datastore_type: etcdv2
cluster: kubernetes
profile::docker::storage::physical_volumes: "/dev/md1"
profile::docker::storage::vg_to_remove: 'todelete'
profile::docker::engine::version: "1.12.6-0~debian-jessie"
profile::docker::engine::packagename: "docker-engine"
profile::docker::engine::declare_service: true
profile::kubernetes::master_fqdn: neon.eqiad.wmnet
profile::kubernetes::master_hosts:
- neon.eqiad.wmnet
profile::kubernetes::infra_pod: 'docker-registry.discovery.wmnet/pause'
profile::kubernetes::use_cni: true
profile::docker::engine::settings:
  bridge: none
  iptables: false
  ip-masq: false
  live-restore: true
profile::base::check_disk_options: -w 10% -c 5% -W 6% -K 3% -l -e -A -i '/(var/lib|run)/(docker|kubelet)/*' --exclude-type=tracefs
profile::calico::kubernetes::calico_version: 2.2.0
profile::calico::kubernetes::docker::registry: docker-registry.discovery.wmnet
profile::kubernetes::node::masquerade_all: false
# This is deprecated, will be removed soon
profile::kubernetes::node::username: 'kubelet'
profile::kubernetes::node::prometheus_url: http://prometheus.svc.eqiad.wmnet/k8s-staging
profile::kubernetes::node::kubelet_username: kubelet
profile::kubernetes::node::kubelet_cluster_dns: "10.64.76.3"
profile::kubernetes::node::kubelet_cluster_domain: 'cluster.local'
# Defined in the private repo
#profile::kubernetes::node::kubelet_token:
profile::kubernetes::node::kubeproxy_username: system:kube-proxy
# Defined in the private repo
#profile::kubernetes::node::kubeproxy_token:
profile::kubernetes::node::kubelet_config: /etc/kubernetes/kubelet_config
profile::kubernetes::node::kubeproxy_config: /etc/kubernetes/kubeproxy_config
profile::kubernetes::node::kubeproxy_metrics_bind_address: 0.0.0.0
profile::rsyslog::kubernetes::kubernetes_url: https://neon.eqiad.wmnet:6443
profile::rsyslog::kubernetes::enable: true
# Define in the private repo
# profile::rsyslog::kubernetes::token
# Use Kernel 4.19 - T262527
profile::base::linux419::enable: true
