cluster: kubernetes-staging
profile::kubernetes::node::packages_from_future: true
profile::calico::kubernetes::calico_version: '3'
profile::base::overlayfs: true
# FIXME: this parameter is not needed anymore, since the docker class
#        doesn't use the version for Buster+.
#        We need to change the related profile and then drop the version.
profile::docker::engine::version: '20.10.5+dfsg1-1+deb11u1'
profile::docker::engine::packagename: "docker.io"
profile::docker::engine::declare_service: true
profile::kubernetes::infra_pod: 'docker-registry.discovery.wmnet/pause'
profile::kubernetes::use_cni: true
profile::docker::engine::settings:
  bridge: none
  iptables: false
  ip-masq: false
  log-opts:
    max-size: 100m
  live-restore: true
profile::monitoring::nrpe_check_disk_options: -w 10% -c 5% -W 6% -K 3% -l -e -A -i '/(var/lib|run)/(docker|kubelet)/*' --exclude-type=tracefs
# Tokens for the calico kubernetes users in private repo at:
#profile::calico::kubernetes::calico_cni::token
#profile::calico::kubernetes::calicoctl::token
profile::kubernetes::node::masquerade_all: false
profile::kubernetes::node::kubelet_cluster_domain: 'cluster.local'
# Defined in the private repo
#profile::kubernetes::node::kubelet_token:
# Defined in the private repo
#profile::kubernetes::node::kubeproxy_token:
profile::kubernetes::node::kubeproxy_metrics_bind_address: 0.0.0.0
profile::rsyslog::kubernetes::enable: true
# Define in the private repo
# profile::rsyslog::kubernetes::token
profile::kubernetes::node::kubelet_ipv6: true
profile::contacts::role_contacts: ['ServiceOps']

profile::dragonfly::dfdaemon::ensure: present
profile::rsyslog::kubernetes::kubernetes_url: https://kubestagemaster.svc.%{::site}.wmnet:6443
profile::kubernetes::master_fqdn: kubestagemaster.svc.%{::site}.wmnet
profile::kubernetes::node::prometheus_url: http://prometheus.svc.%{::site}.wmnet/k8s-staging
# We don't need conftool safe restart scripts on k8s.
profile::lvs::realserver::use_conftool: false
profile::lvs::realserver::pools:
  k8s-ingress-staging: {}
