cluster: graphite
admin::groups:
  - perf-roots
  - graphite-admins
graphite::web::uwsgi_processes: 16
profile::tlsproxy::envoy::global_cert_name: "graphite.discovery.wmnet"
profile::idp::client::httpd::vhost_content: 'profile/idp/client/httpd-graphite.erb'
profile::idp::client::httpd::virtual_host: 'graphite.wikimedia.org'
profile::idp::client::httpd::document_root: '/usr/share/graphite-web'
profile::idp::client::httpd::required_groups:
  - 'cn=ops,ou=groups,dc=wikimedia,dc=org'
  - 'cn=wmf,ou=groups,dc=wikimedia,dc=org'
  - 'cn=nda,ou=groups,dc=wikimedia,dc=org'
profile::idp::client::httpd::proxied_as_https: true
profile::idp::client::httpd::staging: true
