cluster: graphite
admin::groups:
  - perf-roots
  - graphite-admins
graphite::web::uwsgi_processes: 16
profile::tlsproxy::envoy::ensure: present
profile::tlsproxy::envoy::services:
  - server_names: ['*']
    port: 80
profile::tlsproxy::envoy::global_cert_name: "graphite.discovery.wmnet"
profile::tlsproxy::envoy::sni_support: "no"
