profile::base::remote_syslog: []

# ES-specific
elasticsearch::default_instance_params:
    cluster_name: labs-logstash-eqiad
    expected_nodes: 1
    heap_memory: '5G'
    minimum_master_nodes: 1
    recover_after_nodes: 1
    recover_after_time: '1m'
    # Needed to keep from trying to join cirrussearch cluster
    unicast_hosts:
      - deployment-logstash2.deployment-prep.eqiad.wmflabs
    auto_create_index: '+logstash-*,-*'
    cluster_hosts:
      - deployment-logstash2.deployment-prep.eqiad.wmflabs

# Kibana
role::kibana::vhost: logstash-beta.wmflabs.org
role::kibana::serveradmin: root@deployment-logstash2.deployment-prep.eqiad.wmflabs
role::kibana::auth_type: local
role::kibana::auth_realm: "Logstash (ssh deployment-deploy01.deployment-prep.eqiad.wmflabs sudo cat /root/secrets.txt)"
role::kibana::auth_file: /etc/logstash/htpasswd
