profile::calico::kubernetes::bgp_peers:
- kubestagemaster2001.codfw.wmnet
- kubestage2001.codfw.wmnet
- kubestage2002.codfw.wmnet
- cr1-codfw.wikimedia.org
- cr2-codfw.wikimedia.org
profile::kubernetes::master_hosts:
- kubestagemaster2001.codfw.wmnet
profile::kubernetes::node::kubelet_cluster_dns: "10.192.76.3"
profile::monitoring::notifications_enabled: false
profile::kubernetes::cluster_cidr:
  v4: "10.192.75.0/24"
  v6: "2620:0:860:babe::/64"