cluster: eventschemas
profile::lvs::realserver::pools:
  schema:
    services:
      - nginx

profile::tlsproxy::envoy::ensure: present
profile::tlsproxy::envoy::services:
  - server_names: ['*']
    port: 8190
profile::tlsproxy::envoy::global_cert_name: "schema.discovery.wmnet"
profile::tlsproxy::envoy::sni_support: "no"
