fixtures:
    symlinks:
        systemd: "#{source_dir}"
        logrotate: "../../../../logrotate"
        nrpe: "../../../../nrpe"
        rsyslog: "../../../../rsyslog"
        stdlib: "../../../../stdlib"
        wmflib: "../../../../wmflib"
