# SPDX-License-Identifier: Apache-2.0
groups:
- name: webperf_cpu_bechmark
  rules:
  - record: job:webperf_cpubenchmark_seconds:95pct1h
    expr: histogram_quantile(0.95, sum by (le,job) (rate(webperf_cpubenchmark_seconds_bucket[1h])))
  - record: job:webperf_cpubenchmark_seconds:75pct1h
    expr:   histogram_quantile(0.75, sum by (le,job) (rate(webperf_cpubenchmark_seconds_bucket[1h])))
  - record: job:webperf_cpubenchmark_seconds:50pct1h
    expr:   histogram_quantile(0.50, sum by (le,job) (rate(webperf_cpubenchmark_seconds_bucket[1h])))