profile::etcd::replication::origin:
  cluster_name: eqiad.wmnet
  path: /conftool
  servers:
    - conf1004.eqiad.wmnet
    - conf1005.eqiad.wmnet
    - conf1006.eqiad.wmnet
profile::etcd::replication::destination_path: /conftool
profile::etcd::replication::src_port: 4001
# only conf2005 is active
profile::etcd::replication::active: false
profile::zookeeper::cluster_name: main-codfw

# Raise election timeout to account for disk latencies during raid resyncs
# see T162013
profile::etcd::election_timeout: 3000