profile::etcd::replication::origin:
  cluster_name: eqiad.wmnet
  path: /conftool
  servers:
    - conf1004.eqiad.wmnet
    - conf1005.eqiad.wmnet
    - conf1006.eqiad.wmnet
profile::etcd::replication::destination_path: /conftool
profile::etcd::replication::dst_url: https://conf2005.codfw.wmnet:2379
# For nodes with active replication, see hieradata/hosts/conf*.yaml
profile::etcd::replication::active: false
