fixtures:
    symlinks:
        standard: "#{source_dir}"
        base: "../../../../base"
        prometheus: "../../../../prometheus"
        nrpe: "../../../../nrpe"
        ferm: "../../../../ferm"
        exim4: "../../../../exim4"
        stdlib: "../../../../stdlib"
        wmflib: "../../../../wmflib"
