fixtures:
    symlinks:
        standard: "#{source_dir}"
        base: "../../../../base"
        profile: "../../../../profile"
        sslcert: "../../../../sslcert"
        apt: "../../../../apt"
        puppet_statsd: "../../../../puppet_statsd"
        logrotate: "../../../../logrotate"
        rsyslog: "../../../../rsyslog"
        motd: "../../../../motd"
        prometheus: "../../../../prometheus"
        grub: "../../../../grub"
        ssh: "../../../../ssh"
        sysctl: "../../../../sysctl"
        debconf: "../../../../debconf"
        nrpe: "../../../../nrpe"
        kmod: "../../../../kmod"
        initramfs: "../../../../initramfs"
        raid: "../../../../raid"
        sudo: "../../../../sudo"
        monitoring: "../../../../monitoring"
        cumin: "../../../../cumin"
        concat: "../../../../concat"
        diamond: "../../../../diamond"
        systemd: "../../../../systemd"
        role: "../../../../role"
        ferm: "../../../../ferm"
        exim4: "../../../../exim4"
        admin: "../../../../admin"
        apparmor: "../../../../apparmor"
        ntp: "../../../../ntp"
        network: "../../../../network"
        stdlib: "../../../../stdlib"
        wmflib: "../../../../wmflib"
