# Notify the Data Engineering team about services on these hosts
contactgroups: 'admins,analytics'
mgmt_contactgroups: 'admins,analytics'

profile::druid::turnilo::port: 9091
profile::druid::turnilo::monitoring_enabled: false
profile::druid::turnilo::druid_clusters:
  - name: druid-analytics-eqiad
    host: 'an-druid1001.eqiad.wmnet:8082'
    sourceListScan: auto
    sourceListRefreshInterval: 15000
    sourceReintrospectInterval: 120000
    type: druid

profile::contacts::role_contacts: ['Data Engineering']
