# SPDX-License-Identifier: Apache-2.0
---
# yamllint disable rule:line-length
schemes:
  prodbullseye:
    objects: [sdb1]
    accounts: [sdb1]
    containers: [sdb1]
    object-1: [sdb1]
    weight:
      objects: 1000
      accounts: 1000
      containers: 1000
      object-1: 1000

hosts:
  prodbullseye:
    - deployment-ms-be07:
      - immediate
    - deployment-ms-be08:
      - immediate
