# SPDX-License-Identifier: Apache-2.0
fixtures:
    symlinks:
        java: "#{source_dir}"
        alternatives: "../../../../alternatives"
        apt: "../../../../apt"
        stdlib: "../../../../stdlib"
        wmflib: "../../../../wmflib"
