profile::kubernetes::master::service_cluster_ip_range: 10.192.72.0/24
profile::kubernetes::master::etcd_urls:
 - https://kubetcd2004.codfw.wmnet:2379
 - https://kubetcd2005.codfw.wmnet:2379
 - https://kubetcd2006.codfw.wmnet:2379

# Needed to run kubelet on the master node (T290967)
profile::calico::kubernetes::bgp_peers:
- kubemaster2001.codfw.wmnet
- kubemaster2002.codfw.wmnet
- kubernetes2005.codfw.wmnet
- kubernetes2006.codfw.wmnet
- kubernetes2007.codfw.wmnet
- kubernetes2008.codfw.wmnet
- kubernetes2009.codfw.wmnet
- kubernetes2010.codfw.wmnet
- kubernetes2011.codfw.wmnet
- kubernetes2012.codfw.wmnet
- kubernetes2013.codfw.wmnet
- kubernetes2014.codfw.wmnet
- kubernetes2015.codfw.wmnet
- kubernetes2016.codfw.wmnet
- kubernetes2017.codfw.wmnet
- kubernetes2018.codfw.wmnet
- kubernetes2019.codfw.wmnet
- kubernetes2020.codfw.wmnet
- kubernetes2021.codfw.wmnet
- kubernetes2022.codfw.wmnet
- cr1-codfw.wikimedia.org
- cr2-codfw.wikimedia.org
profile::kubernetes::master_hosts:
- kubemaster2001.codfw.wmnet
- kubemaster2002.codfw.wmnet
profile::kubernetes::node::kubelet_cluster_dns: "10.192.72.3"

profile::docker::engine::version: "20.10.5+dfsg1-1+deb11u1"