profile::kubernetes::service_cluster_cidr:
  v4: "10.192.72.0/24"
  v6: "2620:0:860:cabf::/64"

profile::kubernetes::master::etcd_urls:
 - https://kubetcd2004.codfw.wmnet:2379
 - https://kubetcd2005.codfw.wmnet:2379
 - https://kubetcd2006.codfw.wmnet:2379

# Needed to run kubelet on the master node (T290967)
profile::calico::kubernetes::bgp_peers:
- kubemaster2001.codfw.wmnet
- kubemaster2002.codfw.wmnet
- kubernetes2005.codfw.wmnet
- kubernetes2006.codfw.wmnet
- kubernetes2007.codfw.wmnet
- kubernetes2008.codfw.wmnet
- kubernetes2009.codfw.wmnet
- kubernetes2010.codfw.wmnet
- kubernetes2011.codfw.wmnet
- kubernetes2012.codfw.wmnet
- kubernetes2013.codfw.wmnet
- kubernetes2014.codfw.wmnet
- kubernetes2015.codfw.wmnet
- kubernetes2016.codfw.wmnet
- kubernetes2017.codfw.wmnet
- kubernetes2018.codfw.wmnet
- kubernetes2019.codfw.wmnet
- kubernetes2020.codfw.wmnet
- kubernetes2021.codfw.wmnet
- kubernetes2022.codfw.wmnet
- cr1-codfw.wikimedia.org
- cr2-codfw.wikimedia.org
profile::kubernetes::master_hosts:
- kubemaster2001.codfw.wmnet
- kubemaster2002.codfw.wmnet
profile::kubernetes::node::kubelet_cluster_dns: "10.192.72.3"
profile::kubernetes::cluster_cidr:
  v4: "10.194.128.0/18"
  v6: "2620:0:860:cabe::/64"

# Kubernetes 1.23 related common settings (should go from here to common for the eqiad update)
profile::kubernetes::version: '1.23'
profile::calico::kubernetes::calico_version: '3.23'
profile::kubernetes::infra_pod: "docker-registry.discovery.wmnet/pause:3.6-1"
# See "kube-apiserver --help" for a list of available admission plugins
# and details about which of them are enabled by default (e.g. need to be disabled here if you don't want them).
profile::kubernetes::master::admission_plugins:
  enable:
    - PodSecurityPolicy
    # v1.23: Enable DenyServiceExternalIPs because we don't use them
    - DenyServiceExternalIPs
    # v1.23: Limit the access scope of kubelets to only relevant Node and Pod objects
    - NodeRestriction
  disable:
    - StorageObjectInUseProtection
    - PersistentVolumeClaimResize