profile::calico::kubernetes::etcd_endpoints:
- https://kubetcd2004.codfw.wmnet:2379
- https://kubetcd2005.codfw.wmnet:2379
- https://kubetcd2006.codfw.wmnet:2379
profile::calico::kubernetes::bgp_peers:
- kubernetes2001.codfw.wmnet
- kubernetes2002.codfw.wmnet
- kubernetes2003.codfw.wmnet
- kubernetes2004.codfw.wmnet
- kubernetes2005.codfw.wmnet
- kubernetes2006.codfw.wmnet
- cr1-codfw.wikimedia.org
- cr2-codfw.wikimedia.org
# TODO: Migrate to k8s API, calico v2.2 doesn't support anything than etcdv2
profile::calico::kubernetes::calico_datastore_type: etcdv2
# enable this when coredns has been deployed not before.
profile::kubernetes::node::kubelet_cluster_dns: "10.192.72.3"
profile::kubernetes::node::kubelet_cluster_domain: 'cluster.local'
profile::rsyslog::kubernetes::kubernetes_url: https://kubemaster.svc.codfw.wmnet:6443
# Define in the private repo
# profile::rsyslog::kubernetes::token
