- name: default
  also_notifies: []
  attributes: {}
  description: Pool for eqiad1/cloudservices1003
  id: 794ccc2c-d751-44fe-b57f-8894c9f5c842
  nameservers:
  - host: 208.80.154.135
    port: 53
  - host: 208.80.154.11
    port: 53
  ns_records:
  - hostname: ns0.openstack.eqiad1.wikimediacloud.org.
    priority: 10
  - hostname: ns1.openstack.eqiad1.wikimediacloud.org.
    priority: 11
  targets:
  - masters:
    - host: 208.80.154.135
      port: 5354
    options:
      api_endpoint: http://208.80.154.135:8081
      api_token: changeme
      host: 208.80.154.135
      port: '53'
    type: pdns4
  - masters:
    - host: 208.80.154.135
      port: 5354
    options:
      api_endpoint: http://208.80.154.11:8081
      api_token: changeme
      host: 208.80.154.11
      port: '53'
    type: pdns4
