- name: default
  also_notifies: []
  attributes: {}
  description: Pool built from configuration on cloudservices2002-dev
  id: 794ccc2c-d751-44fe-b57f-8894c9f5c842
  nameservers:
  - host: 208.80.153.76
    port: 53
  ns_records:
  - hostname: codfw1dev-ns0.wikimedia.org.
    priority: 1

  targets:
  - masters:
    - host: 208.80.153.76
      port: 5354
    options:
        host: 208.80.153.76
        port: 53
        api_endpoint: http://208.80.153.76:8081
        api_token: changeme
    type: pdns4
