profile::etcd::replication::origin:
  cluster_name: codfw.wmnet
  path: /conftool
  servers:
    - conf2001.codfw.wmnet
    - conf2002.codfw.wmnet
    - conf2003.codfw.wmnet
profile::etcd::replication::destination_path: /conftool
profile::etcd::replication::dst_url: https://conf1005.eqiad.wmnet:2379
# only conf1005 is active if this is not the master DC.
profile::etcd::replication::active: false