prometheus::server::memory_chunks: 3145728
prometheus::server::max_chunks_to_persist: 1048576
lvs::realserver::realserver_ips:
 - 10.2.2.25
profile::prometheus::ops::enable_thanos_upload: true
# A hash containing configuration for kubernetes clusters.
profile::prometheus::kubernetes::clusters:
  k8s:
    enabled: true
    master_host: 'kubemaster.svc.eqiad.wmnet'
    port: 9906
    class_name: role::kubernetes::worker
  k8s-staging:
    enabled: true
    # TODO: Switch to that
    # master_host: 'kubestagemaster.svc.eqiad.wmnet'
    master_host: neon.eqiad.wmnet
    port: 9907
    class_name: role::kubernetes::staging::worker
# In the private repo a stanza like the following is required
# profile::prometheus::kubernetes::cluster_tokens:
# k8s:
#   client_token: eqiaddummy
# k8s-staging:
#   client_token: eqiaddummystaging
